"""initial model design with users

Revision ID: 3eaefcea9647
Revises: a86c35eec038
Create Date: 2026-03-17 18:07:42.515425
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3eaefcea9647"
down_revision: str | None = "a86c35eec038"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.add_column("exercises", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_exercises_name"), table_name="exercises")
    op.create_index(op.f("ix_exercises_name"), "exercises", ["name"], unique=False)
    op.create_unique_constraint(None, "exercises", ["user_id", "name"])
    op.create_foreign_key(
        None, "exercises", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "workouts",
        sa.Column(
            "workout_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
    )
    op.add_column("workouts", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "workouts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("workouts", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts",
        sa.Column(
            "date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "workouts", type_="foreignkey")
    op.drop_column("workouts", "user_id")
    op.drop_column("workouts", "workout_date")
    op.drop_constraint(None, "exercises", type_="foreignkey")
    op.drop_constraint(None, "exercises", type_="unique")
    op.drop_index(op.f("ix_exercises_name"), table_name="exercises")
    op.create_index(op.f("ix_exercises_name"), "exercises", ["name"], unique=True)
    op.drop_column("exercises", "user_id")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
