"""

Revision ID: 952f51ffb227
Revises: 3eaefcea9647
Create Date: 2026-03-20 13:08:20.547335
"""

from collections.abc import Sequence

from alembic import op

revision: str = "952f51ffb227"
down_revision: str | None = "3eaefcea9647"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "sets", ["workout_exercise_id", "set_number"])
    op.create_unique_constraint(None, "workout_exercises", ["workout_id", "order"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_exercises", type_="unique")
    op.drop_constraint(None, "sets", type_="unique")
    # ### end Alembic commands ###
