"""improved timezone handling and added workout name

Revision ID: 97250441fb42
Revises: 952f51ffb227
Create Date: 2026-03-23 14:16:35.605015
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "97250441fb42"
down_revision: str | None = "952f51ffb227"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("name", sa.String(255), nullable=True))
    op.create_index(op.f("ix_workouts_name"), "workouts", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workouts_name"), table_name="workouts")
    op.drop_column("workouts", "name")
    # ### end Alembic commands ###
